const products = [
  {
    title: "Noise-Cancelling Wireless Headphones",
    description: "Premium over-ear headphones with immersive sound and 30-hour battery life.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    category: "electronics",
    stock: 20,
    price: 149.99,
    rating: 4.7,
    featured: true,
    trending: true,
  },
  {
    title: "Smart Fitness Watch",
    description: "Track workouts, heart rate, and notifications with this sleek smart watch.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
    category: "electronics",
    stock: 16,
    price: 99.99,
    rating: 4.5,
    featured: true,
    trending: false,
  },
  {
    title: "Classic Denim Jacket",
    description: "Stylish regular-fit denim jacket perfect for all seasons.",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800",
    category: "fashion",
    stock: 28,
    price: 59.99,
    rating: 4.4,
    featured: false,
    trending: true,
  },
  {
    title: "Minimalist Everyday T-Shirt",
    description: "Soft cotton t-shirt with a clean fit and breathable comfort.",
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800",
    category: "fashion",
    stock: 45,
    price: 19.99,
    rating: 4.3,
    featured: false,
    trending: false,
  },
  {
    title: "Urban Runner Sneakers",
    description: "Lightweight running shoes with cushioned sole and modern style.",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
    category: "shoes",
    stock: 24,
    price: 79.99,
    rating: 4.6,
    featured: true,
    trending: true,
  },
  {
    title: "Leather Slip-On Loafers",
    description: "Comfort-focused leather loafers for office and casual wear.",
    image: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800",
    category: "shoes",
    stock: 18,
    price: 69.99,
    rating: 4.2,
    featured: false,
    trending: false,
  },
  {
    title: "Premium Leather Wallet",
    description: "Compact bifold wallet with RFID protection and multiple card slots.",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800",
    category: "accessories",
    stock: 50,
    price: 29.99,
    rating: 4.5,
    featured: true,
    trending: false,
  },
  {
    title: "Polarized Sunglasses",
    description: "UV-protected polarized sunglasses with lightweight frame design.",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800",
    category: "accessories",
    stock: 30,
    price: 34.99,
    rating: 4.4,
    featured: false,
    trending: true,
  },
];

module.exports = products;
